/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.aksoyali;

import java.awt.Desktop;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.LineNumberReader;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.nio.charset.Charset;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.design.*;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Ali
 */
public class MalzemeGirisiGUI extends javax.swing.JFrame {

    /**
     * Creates new form MalzemeGirisiGUI
     */
    public MalzemeGirisiGUI() {
        initComponents();
         this.setLocationRelativeTo(getRootPane());//Frame ekranın ortasında açılır
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        pnlMalzeme = new javax.swing.JPanel();
        txtmalzemeMarkasi = new javax.swing.JTextField();
        lblmalzemeModeli = new javax.swing.JLabel();
        lblmalzemeAdi = new javax.swing.JLabel();
        lblmalzemeDataSheet = new javax.swing.JLabel();
        lblmalzemeFiyati = new javax.swing.JLabel();
        btnDataSheetSec = new javax.swing.JButton();
        lblmalzemeMarkasi = new javax.swing.JLabel();
        txtmalzemeAdi = new javax.swing.JTextField();
        txtmalzemeGrubu = new javax.swing.JTextField();
        txtmalzemeAltGrubu = new javax.swing.JTextField();
        txtmalzemeModeli = new javax.swing.JTextField();
        lblmalzemeGrubu = new javax.swing.JLabel();
        lblmalzemeAltGrubu = new javax.swing.JLabel();
        txtmalzemeFiyati = new javax.swing.JTextField();
        txtmalzemeDataSheet = new javax.swing.JTextField();
        pnlMalzemeButonlar = new javax.swing.JPanel();
        btnMalzemeKaydet = new javax.swing.JButton();
        btnMalzemeSil = new javax.swing.JButton();
        btnMalzemeDuzenle = new javax.swing.JButton();
        btnMalzemeYazdir = new javax.swing.JButton();
        btnMalzemeFormuTemizle = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblmalzemeBirimi = new javax.swing.JLabel();
        cbmalzemeBirimi = new javax.swing.JComboBox();
        lblparaBirimi = new javax.swing.JLabel();
        cbparaBirimi = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblmalzemeDataSheet1 = new javax.swing.JLabel();
        txtmalzemeSartname = new javax.swing.JTextField();
        btnDataSheetSec1 = new javax.swing.JButton();
        pnlMalzemeArama = new javax.swing.JPanel();
        lblAramaMalzemeAdi = new javax.swing.JLabel();
        lblAramaMalzemeMarkasi = new javax.swing.JLabel();
        lblAramaMesaj = new javax.swing.JLabel();
        txtAramaMalzemeAdi = new javax.swing.JTextField();
        txtAramaMalzemeMarkasi = new javax.swing.JTextField();
        btnMalzemeExport = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMalzeme = new javax.swing.JTable();
        btnAcMalzemeImportGUI = new javax.swing.JButton();
        btnMalzemeRefresh = new javax.swing.JButton();
        btnMalzemeExcelAktar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuDosya = new javax.swing.JMenu();
        menuItemExportExcel = new javax.swing.JMenuItem();
        menuItemExportCsv = new javax.swing.JMenuItem();
        menuItemImportCsv = new javax.swing.JMenuItem();
        menuItemYazdir = new javax.swing.JMenuItem();
        menuItemCikis = new javax.swing.JMenuItem();
        menuDuzen = new javax.swing.JMenu();
        menuItemToplamMalzeme = new javax.swing.JMenuItem();
        menuYardim = new javax.swing.JMenu();
        menuItemHakkinda = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MALZEME GİRİŞ");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlMalzeme.setBackground(new java.awt.Color(153, 255, 255));
        pnlMalzeme.setBorder(javax.swing.BorderFactory.createTitledBorder("MALZEME"));

        lblmalzemeModeli.setText("Malzeme Modeli");

        lblmalzemeAdi.setText("Malzeme Adı");

        lblmalzemeDataSheet.setText("Malzeme Data Sheet");

        lblmalzemeFiyati.setText("Malzeme Fiyatı");

        btnDataSheetSec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/open.png"))); // NOI18N
        btnDataSheetSec.setText("SEÇ");
        btnDataSheetSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataSheetSecActionPerformed(evt);
            }
        });

        lblmalzemeMarkasi.setText("Malzeme Markası");

        lblmalzemeGrubu.setText("Malzeme Grubu");

        lblmalzemeAltGrubu.setText("Malzeme Alt Grubu");

        txtmalzemeDataSheet.setEditable(false);

        pnlMalzemeButonlar.setBackground(new java.awt.Color(153, 255, 255));

        btnMalzemeKaydet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save.png"))); // NOI18N
        btnMalzemeKaydet.setText("KAYDET");
        btnMalzemeKaydet.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnMalzemeKaydet.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnMalzemeKaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMalzemeKaydetActionPerformed(evt);
            }
        });

        btnMalzemeSil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete.png"))); // NOI18N
        btnMalzemeSil.setText("SİL");
        btnMalzemeSil.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnMalzemeSil.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnMalzemeSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMalzemeSilActionPerformed(evt);
            }
        });

        btnMalzemeDuzenle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit.png"))); // NOI18N
        btnMalzemeDuzenle.setText("DÜZENLE");
        btnMalzemeDuzenle.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnMalzemeDuzenle.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnMalzemeDuzenle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMalzemeDuzenleActionPerformed(evt);
            }
        });

        btnMalzemeYazdir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/print.png"))); // NOI18N
        btnMalzemeYazdir.setText("YAZDIR");
        btnMalzemeYazdir.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnMalzemeYazdir.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnMalzemeYazdir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMalzemeYazdirActionPerformed(evt);
            }
        });

        btnMalzemeFormuTemizle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/temizle.png"))); // NOI18N
        btnMalzemeFormuTemizle.setText("FORMU TEMİZLE");
        btnMalzemeFormuTemizle.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnMalzemeFormuTemizle.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnMalzemeFormuTemizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMalzemeFormuTemizleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMalzemeButonlarLayout = new javax.swing.GroupLayout(pnlMalzemeButonlar);
        pnlMalzemeButonlar.setLayout(pnlMalzemeButonlarLayout);
        pnlMalzemeButonlarLayout.setHorizontalGroup(
            pnlMalzemeButonlarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMalzemeButonlarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMalzemeButonlarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMalzemeSil, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMalzemeDuzenle)
                    .addComponent(btnMalzemeYazdir, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMalzemeFormuTemizle, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(pnlMalzemeButonlarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlMalzemeButonlarLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnMalzemeKaydet)
                    .addContainerGap(20, Short.MAX_VALUE)))
        );

        pnlMalzemeButonlarLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnMalzemeDuzenle, btnMalzemeFormuTemizle, btnMalzemeKaydet, btnMalzemeSil, btnMalzemeYazdir});

        pnlMalzemeButonlarLayout.setVerticalGroup(
            pnlMalzemeButonlarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMalzemeButonlarLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(btnMalzemeSil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMalzemeDuzenle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMalzemeYazdir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMalzemeFormuTemizle)
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(pnlMalzemeButonlarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlMalzemeButonlarLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnMalzemeKaydet)
                    .addContainerGap(207, Short.MAX_VALUE)))
        );

        pnlMalzemeButonlarLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnMalzemeDuzenle, btnMalzemeKaydet, btnMalzemeSil, btnMalzemeYazdir});

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("*");
        jLabel1.setToolTipText("ZORUNLU ALAN");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("*");
        jLabel2.setToolTipText("ZORUNLU ALAN");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("*");
        jLabel3.setToolTipText("ZORUNLU ALAN");

        lblmalzemeBirimi.setText("Malzeme Birimi");

        cbmalzemeBirimi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Adet", "Metre", "Takım" }));

        lblparaBirimi.setText("Para Birimi");

        cbparaBirimi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TL", "USD", "EURO" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("*");
        jLabel4.setToolTipText("ZORUNLU ALAN");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("*");
        jLabel5.setToolTipText("ZORUNLU ALAN");

        lblmalzemeDataSheet1.setText("Şartname");

        txtmalzemeSartname.setEditable(false);

        btnDataSheetSec1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/open.png"))); // NOI18N
        btnDataSheetSec1.setText("SEÇ");
        btnDataSheetSec1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataSheetSec1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMalzemeLayout = new javax.swing.GroupLayout(pnlMalzeme);
        pnlMalzeme.setLayout(pnlMalzemeLayout);
        pnlMalzemeLayout.setHorizontalGroup(
            pnlMalzemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMalzemeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMalzemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMalzemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMalzemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMalzemeLayout.createSequentialGroup()
                        .addGroup(pnlMalzemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblmalzemeModeli, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(lblmalzemeAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblmalzemeFiyati, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(lblmalzemeDataSheet, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(lblmalzemeMarkasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblmalzemeDataSheet1, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlMalzemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMalzemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMalzemeLayout.createSequentialGroup()
                                    .addComponent(txtmalzemeDataSheet)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnDataSheetSec))
                                .addComponent(txtmalzemeAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(pnlMalzemeLayout.createSequentialGroup()
                                    .addComponent(txtmalzemeFiyati)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblparaBirimi)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbparaBirimi, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblmalzemeBirimi)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbmalzemeBirimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlMalzemeLayout.createSequentialGroup()
                                    .addComponent(txtmalzemeSartname)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnDataSheetSec1)))
                            .addComponent(txtmalzemeModeli, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmalzemeMarkasi, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlMalzemeLayout.createSequentialGroup()
                        .addGroup(pnlMalzemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblmalzemeAltGrubu, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(lblmalzemeGrubu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlMalzemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtmalzemeGrubu, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmalzemeAltGrubu, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24)
                .addComponent(pnlMalzemeButonlar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlMalzemeLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDataSheetSec, btnDataSheetSec1});

        pnlMalzemeLayout.setVerticalGroup(
            pnlMalzemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMalzemeLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(pnlMalzemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblmalzemeGrubu)
                    .addComponent(txtmalzemeGrubu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMalzemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmalzemeAltGrubu)
                    .addComponent(txtmalzemeAltGrubu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMalzemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmalzemeMarkasi)
                    .addComponent(txtmalzemeMarkasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMalzemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmalzemeModeli)
                    .addComponent(txtmalzemeModeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMalzemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmalzemeAdi)
                    .addComponent(jLabel1)
                    .addComponent(txtmalzemeAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(pnlMalzemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMalzemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblmalzemeBirimi)
                        .addComponent(cbmalzemeBirimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMalzemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtmalzemeFiyati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblparaBirimi)
                        .addComponent(cbparaBirimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblmalzemeFiyati)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addGroup(pnlMalzemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblmalzemeDataSheet, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlMalzemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDataSheetSec, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtmalzemeDataSheet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlMalzemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblmalzemeDataSheet1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlMalzemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDataSheetSec1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtmalzemeSartname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlMalzemeLayout.createSequentialGroup()
                .addComponent(pnlMalzemeButonlar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlMalzemeLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnDataSheetSec, btnDataSheetSec1, txtmalzemeDataSheet, txtmalzemeFiyati, txtmalzemeSartname});

        pnlMalzemeArama.setBackground(new java.awt.Color(153, 255, 255));
        pnlMalzemeArama.setBorder(javax.swing.BorderFactory.createTitledBorder("ARAMA"));

        lblAramaMalzemeAdi.setText("Malzeme Adı: ");

        lblAramaMalzemeMarkasi.setText("Malzeme Markası: ");

        lblAramaMesaj.setText("Mesaj: ");

        txtAramaMalzemeAdi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAramaMalzemeAdiKeyReleased(evt);
            }
        });

        txtAramaMalzemeMarkasi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAramaMalzemeMarkasiKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlMalzemeAramaLayout = new javax.swing.GroupLayout(pnlMalzemeArama);
        pnlMalzemeArama.setLayout(pnlMalzemeAramaLayout);
        pnlMalzemeAramaLayout.setHorizontalGroup(
            pnlMalzemeAramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMalzemeAramaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMalzemeAramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMalzemeAramaLayout.createSequentialGroup()
                        .addComponent(lblAramaMesaj)
                        .addGap(60, 60, 60))
                    .addGroup(pnlMalzemeAramaLayout.createSequentialGroup()
                        .addGroup(pnlMalzemeAramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAramaMalzemeMarkasi, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addGroup(pnlMalzemeAramaLayout.createSequentialGroup()
                                .addComponent(lblAramaMalzemeAdi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(21, 21, 21)))
                        .addGap(24, 24, 24)
                        .addGroup(pnlMalzemeAramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAramaMalzemeAdi, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(txtAramaMalzemeMarkasi))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlMalzemeAramaLayout.setVerticalGroup(
            pnlMalzemeAramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMalzemeAramaLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(pnlMalzemeAramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAramaMalzemeAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMalzemeAramaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblAramaMalzemeAdi)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMalzemeAramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAramaMalzemeMarkasi)
                    .addComponent(txtAramaMalzemeMarkasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAramaMesaj)
                .addContainerGap())
        );

        btnMalzemeExport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/extract.png"))); // NOI18N
        btnMalzemeExport.setText("Malzemeleri Dışa Aktar CSV");
        btnMalzemeExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMalzemeExportActionPerformed(evt);
            }
        });

        tableMalzeme.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        tableMalzeme.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tableMalzeme.setForeground(new java.awt.Color(0, 102, 51));
        tableMalzeme.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableMalzeme.setSelectionBackground(new java.awt.Color(0, 0, 0));
        tableMalzeme.setSelectionForeground(new java.awt.Color(255, 255, 102));
        tableMalzeme.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableMalzeme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMalzemeMouseClicked(evt);
            }
        });
        tableMalzeme.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableMalzemeKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tableMalzeme);

        btnAcMalzemeImportGUI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/import.png"))); // NOI18N
        btnAcMalzemeImportGUI.setText("Malzemeleri İçe Aktar");
        btnAcMalzemeImportGUI.setPreferredSize(new java.awt.Dimension(167, 33));
        btnAcMalzemeImportGUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcMalzemeImportGUIActionPerformed(evt);
            }
        });

        btnMalzemeRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/refresh.png"))); // NOI18N
        btnMalzemeRefresh.setText("Tabloyu Tazele");
        btnMalzemeRefresh.setPreferredSize(new java.awt.Dimension(167, 33));
        btnMalzemeRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMalzemeRefreshActionPerformed(evt);
            }
        });

        btnMalzemeExcelAktar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/excel.png"))); // NOI18N
        btnMalzemeExcelAktar.setText("Malzemeleri Dışa Aktar EXCEL");
        btnMalzemeExcelAktar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMalzemeExcelAktarActionPerformed(evt);
            }
        });

        menuDosya.setText("Dosya");

        menuItemExportExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exporexcel16.png"))); // NOI18N
        menuItemExportExcel.setText("Export Excel");
        menuItemExportExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMalzemeExcelAktarActionPerformed(evt);
            }
        });
        menuDosya.add(menuItemExportExcel);

        menuItemExportCsv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/export16.png"))); // NOI18N
        menuItemExportCsv.setText("Export CSV");
        menuItemExportCsv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMalzemeExportActionPerformed(evt);
            }
        });
        menuDosya.add(menuItemExportCsv);

        menuItemImportCsv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/impor16.png"))); // NOI18N
        menuItemImportCsv.setText("Import CSV");
        menuItemImportCsv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcMalzemeImportGUIActionPerformed(evt);
            }
        });
        menuDosya.add(menuItemImportCsv);

        menuItemYazdir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/print16.png"))); // NOI18N
        menuItemYazdir.setText("Yazdır");
        menuItemYazdir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMalzemeYazdirActionPerformed(evt);
            }
        });
        menuDosya.add(menuItemYazdir);

        menuItemCikis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cıkıs16.png"))); // NOI18N
        menuItemCikis.setText("Çıkış");
        menuItemCikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCikisActionPerformed(evt);
            }
        });
        menuDosya.add(menuItemCikis);

        jMenuBar1.add(menuDosya);

        menuDuzen.setText("Düzen");

        menuItemToplamMalzeme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sum1.png"))); // NOI18N
        menuItemToplamMalzeme.setText("Toplam Malzeme Sayısı");
        menuItemToplamMalzeme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemToplamMalzemeActionPerformed(evt);
            }
        });
        menuDuzen.add(menuItemToplamMalzeme);

        jMenuBar1.add(menuDuzen);

        menuYardim.setText("Yardım");

        menuItemHakkinda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/hakkımızda16.png"))); // NOI18N
        menuItemHakkinda.setText("Hakkında");
        menuItemHakkinda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemHakkindaActionPerformed(evt);
            }
        });
        menuYardim.add(menuItemHakkinda);

        jMenuBar1.add(menuYardim);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1177, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlMalzeme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(btnMalzemeExcelAktar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnMalzemeRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(btnMalzemeExport)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnAcMalzemeImportGUI, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(pnlMalzemeArama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(31, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnMalzemeExcelAktar, btnMalzemeExport});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(pnlMalzemeArama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMalzemeExport)
                            .addComponent(btnAcMalzemeImportGUI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMalzemeRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMalzemeExcelAktar)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlMalzeme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAcMalzemeImportGUI, btnMalzemeExcelAktar, btnMalzemeExport});

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Connection baglanti = null;
    ResultSet resultSet = null;
  //  Statement statement = null;
    PreparedStatement preparedStatement = null;
//    CallableStatement callableStatement = null;
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        baglanti=Mysqlbaglantisi.baglan();

        malzemeleriTabloyaGetir();
                kullanicininYetkileriniBul(); 
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (baglanti != null) {

            try {
                baglanti.close();
            } catch (Exception e) {
            }

        }


        if (resultSet != null) {
            try {
                resultSet.close();
            } catch (Exception e) {
            }
        }


//        if (statement != null) {
//            try {
//                statement.close();
//            } catch (Exception e) {
//            }
//        }

        if (preparedStatement != null) {
            try {
                preparedStatement.close();
            } catch (Exception e) {
            }
        }

//        if (callableStatement != null) {
//            try {
//                callableStatement.close();
//            } catch (Exception e) {
//            }
//        }
    }//GEN-LAST:event_formWindowClosing

    private void btnMalzemeKaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMalzemeKaydetActionPerformed
        malzemeKaydet();
    }//GEN-LAST:event_btnMalzemeKaydetActionPerformed

    private void btnMalzemeSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMalzemeSilActionPerformed
        malzemeSil();
    }//GEN-LAST:event_btnMalzemeSilActionPerformed

    private void btnMalzemeDuzenleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMalzemeDuzenleActionPerformed
        malzemeGuncelle();
    }//GEN-LAST:event_btnMalzemeDuzenleActionPerformed

    private void txtAramaMalzemeAdiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAramaMalzemeAdiKeyReleased
        aramaYap();
    }//GEN-LAST:event_txtAramaMalzemeAdiKeyReleased

    private void txtAramaMalzemeMarkasiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAramaMalzemeMarkasiKeyReleased
        aramaYap();
    }//GEN-LAST:event_txtAramaMalzemeMarkasiKeyReleased

    private void btnDataSheetSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataSheetSecActionPerformed
        JFileChooser fileopen = new JFileChooser();
        FileFilter filter = new FileNameExtensionFilter("PDF files", "pdf");
        fileopen.addChoosableFileFilter(filter);
        int answer = fileopen.showDialog(null, "Open file");
        if (answer == JFileChooser.APPROVE_OPTION) {//Seçim yapılırsa
            File file = fileopen.getSelectedFile();
            txtmalzemeDataSheet.setText(file.toString());//txtbox a seçilen adres yazdırılır.
        }
    }//GEN-LAST:event_btnDataSheetSecActionPerformed

    private void btnMalzemeYazdirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMalzemeYazdirActionPerformed
        malzemeYazdir();

    }//GEN-LAST:event_btnMalzemeYazdirActionPerformed
    public void exportTable(JTable table, File file) throws IOException {

        TableModel model = table.getModel();

//        OutputStreamWriter fw = new OutputStreamWriter(new FileOutputStream("some_output.utf8"),
//                Charset.forName("ISO-8859-9").newEncoder() );
        
        FileWriter fw = new FileWriter(file+".csv");
        

        for (int i = 0; i < model.getRowCount(); i++) {
            for (int j = 0; j < model.getColumnCount(); j++) {
                if(model.getValueAt(i, j).toString().trim().equals("")){
                      fw.write(model.getValueAt(i, j).toString() + " ;"); 
                }
                else{
                fw.write(model.getValueAt(i, j).toString() + ";");
               // System.out.print(model.getValueAt(i, j).toString() + ";");
                }

            }

            fw.write("\n");
            //System.out.print("\n");
        }

        fw.close();

    }
    private void btnMalzemeExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMalzemeExportActionPerformed
        JFileChooser fileopen = new JFileChooser();
        FileFilter filter = new FileNameExtensionFilter("CSV files", "csv");
        fileopen.addChoosableFileFilter(filter);
        int answer = fileopen.showDialog(null, "Save file");
        
        if (answer == JFileChooser.APPROVE_OPTION) {//Ok a basılmışsa
              File f = fileopen.getSelectedFile();
             JOptionPane.showMessageDialog(null, "Dosya Kaydedildi", "Malzeme Csv Kayit",JOptionPane.INFORMATION_MESSAGE);
                   try {
 
            exportTable(tableMalzeme, f);
        } catch (IOException ex) {
        }
        
        }   
        

    }//GEN-LAST:event_btnMalzemeExportActionPerformed

    private void btnMalzemeFormuTemizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMalzemeFormuTemizleActionPerformed
        formuTemizle();
        malzemeleriTabloyaGetir();//jtablemalzemeyi tazeler.
       btnMalzemeDuzenle.setEnabled(false);
       
    }//GEN-LAST:event_btnMalzemeFormuTemizleActionPerformed

    private void btnAcMalzemeImportGUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcMalzemeImportGUIActionPerformed
        MalzemeImportGUI malzemeImportGUI=new MalzemeImportGUI();
        malzemeImportGUI.setVisible(true);
    }//GEN-LAST:event_btnAcMalzemeImportGUIActionPerformed

    private void tableMalzemeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableMalzemeKeyReleased
        tablodakiMalzemeleriTxtFieldlaraGetir();
        
    }//GEN-LAST:event_tableMalzemeKeyReleased

    private void tableMalzemeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMalzemeMouseClicked
        tablodakiMalzemeleriTxtFieldlaraGetir();
    }//GEN-LAST:event_tableMalzemeMouseClicked

    private void btnMalzemeRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMalzemeRefreshActionPerformed
       malzemeleriTabloyaGetir();
    }//GEN-LAST:event_btnMalzemeRefreshActionPerformed
public void exportExcelTable(JTable table, File file) throws IOException {
        TableModel model = table.getModel();
        FileWriter out = new FileWriter(file + ".xls");
        String bosluklariDuzelt = null;
       
         out.write("SıraNO"+ " \t");
        
        for (int i = 1; i < model.getColumnCount()-2; i++) {
            out.write(model.getColumnName(i) + " \t");
        }
        out.write("\n");
        
        
        
        int sayac=1;
        for (int i = 0; i < model.getRowCount(); i++) {
              out.write(sayac+" \t");
            for (int j = 1; j < model.getColumnCount()-2; j++) {


                bosluklariDuzelt = model.getValueAt(i, j).toString().replaceAll(" ", "_");


                out.write(bosluklariDuzelt + " \t");

            }
            out.write("\n");
            sayac++;
        }

        out.close();

    }

    private void btnMalzemeExcelAktarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMalzemeExcelAktarActionPerformed
  
            
        JFileChooser fileopen = new JFileChooser();
        FileFilter filter = new FileNameExtensionFilter("EXCEL files", "xls");
        fileopen.addChoosableFileFilter(filter);
        int answer = fileopen.showDialog(null, "Save file");
        
        if (answer == JFileChooser.APPROVE_OPTION) {//Ok a basılmışsa
              File f = fileopen.getSelectedFile();
             JOptionPane.showMessageDialog(null, "Dosya Kaydedildi", "Malzeme XLS Kayit",JOptionPane.INFORMATION_MESSAGE);
                   try {
 
            exportExcelTable(tableMalzeme, f);
        } catch (IOException ex) {
        }
        
        }   
    }//GEN-LAST:event_btnMalzemeExcelAktarActionPerformed

    private void menuItemHakkindaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemHakkindaActionPerformed
           Hakkimizda hakkimizda=new Hakkimizda();
        hakkimizda.setVisible(true);
    }//GEN-LAST:event_menuItemHakkindaActionPerformed

    private void menuItemCikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCikisActionPerformed
       System.exit(0);
    }//GEN-LAST:event_menuItemCikisActionPerformed

    private void menuItemToplamMalzemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemToplamMalzemeActionPerformed
                 JOptionPane.showMessageDialog(null,  "Toplam Malzeme Sayısı="+tableMalzeme.getRowCount()
            , "Toplam Malzeme Sayısı", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_menuItemToplamMalzemeActionPerformed

    private void btnDataSheetSec1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataSheetSec1ActionPerformed
      JFileChooser fileopen = new JFileChooser();
        FileFilter filter = new FileNameExtensionFilter("PDF Files", "pdf");
        fileopen.addChoosableFileFilter(filter);
        int answer = fileopen.showDialog(null, "Open file");
        if (answer == JFileChooser.APPROVE_OPTION) {//Seçim yapılırsa
            File file = fileopen.getSelectedFile();
            txtmalzemeSartname.setText(file.toString());//txtbox a seçilen adres yazdırılır.
        }
    }//GEN-LAST:event_btnDataSheetSec1ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MalzemeGirisiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MalzemeGirisiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MalzemeGirisiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MalzemeGirisiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MalzemeGirisiGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcMalzemeImportGUI;
    private javax.swing.JButton btnDataSheetSec;
    private javax.swing.JButton btnDataSheetSec1;
    private javax.swing.JButton btnMalzemeDuzenle;
    private javax.swing.JButton btnMalzemeExcelAktar;
    private javax.swing.JButton btnMalzemeExport;
    private javax.swing.JButton btnMalzemeFormuTemizle;
    private javax.swing.JButton btnMalzemeKaydet;
    private javax.swing.JButton btnMalzemeRefresh;
    private javax.swing.JButton btnMalzemeSil;
    private javax.swing.JButton btnMalzemeYazdir;
    private javax.swing.JComboBox cbmalzemeBirimi;
    private javax.swing.JComboBox cbparaBirimi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAramaMalzemeAdi;
    private javax.swing.JLabel lblAramaMalzemeMarkasi;
    private javax.swing.JLabel lblAramaMesaj;
    private javax.swing.JLabel lblmalzemeAdi;
    private javax.swing.JLabel lblmalzemeAltGrubu;
    private javax.swing.JLabel lblmalzemeBirimi;
    private javax.swing.JLabel lblmalzemeDataSheet;
    private javax.swing.JLabel lblmalzemeDataSheet1;
    private javax.swing.JLabel lblmalzemeFiyati;
    private javax.swing.JLabel lblmalzemeGrubu;
    private javax.swing.JLabel lblmalzemeMarkasi;
    private javax.swing.JLabel lblmalzemeModeli;
    private javax.swing.JLabel lblparaBirimi;
    private javax.swing.JMenu menuDosya;
    private javax.swing.JMenu menuDuzen;
    private javax.swing.JMenuItem menuItemCikis;
    private javax.swing.JMenuItem menuItemExportCsv;
    private javax.swing.JMenuItem menuItemExportExcel;
    private javax.swing.JMenuItem menuItemHakkinda;
    private javax.swing.JMenuItem menuItemImportCsv;
    private javax.swing.JMenuItem menuItemToplamMalzeme;
    private javax.swing.JMenuItem menuItemYazdir;
    private javax.swing.JMenu menuYardim;
    private javax.swing.JPanel pnlMalzeme;
    private javax.swing.JPanel pnlMalzemeArama;
    private javax.swing.JPanel pnlMalzemeButonlar;
    private javax.swing.JTable tableMalzeme;
    private javax.swing.JTextField txtAramaMalzemeAdi;
    private javax.swing.JTextField txtAramaMalzemeMarkasi;
    private javax.swing.JTextField txtmalzemeAdi;
    private javax.swing.JTextField txtmalzemeAltGrubu;
    private javax.swing.JTextField txtmalzemeDataSheet;
    private javax.swing.JTextField txtmalzemeFiyati;
    private javax.swing.JTextField txtmalzemeGrubu;
    private javax.swing.JTextField txtmalzemeMarkasi;
    private javax.swing.JTextField txtmalzemeModeli;
    private javax.swing.JTextField txtmalzemeSartname;
    // End of variables declaration//GEN-END:variables

    

   
        
 
    private void malzemeleriTabloyaGetir() {
//        try {
//            String tabloyuGuncelleSorgusu = "SELECT * FROM tblmalzemeler ORDER BY malzemeID";
//            preparedStatement = baglanti.prepareStatement(tabloyuGuncelleSorgusu);
//            resultSet = preparedStatement.executeQuery();
//   tableMalzeme.setModel(DbUtils.resultSetToTableModel(resultSet)
//        );
//          } catch (Exception e) {
//        }
        
        
        try {
            String tabloyuGuncelleSorgusu = "SELECT * FROM tblmalzemeler ORDER BY malzemeID";
            preparedStatement = baglanti.prepareStatement(tabloyuGuncelleSorgusu);
            resultSet = preparedStatement.executeQuery();
   tableMalzeme.setModel(DbUtils.resultSetToTableModel(resultSet));
   tableMalzeme.getModel().addTableModelListener(new TableModelListener(){
                @Override
                public void tableChanged(TableModelEvent e) {
                    malzemeleriTabloyaGetir();
                }                       
            });
      } catch (Exception e) {
        }
        }
    
 

    private void malzemeKaydet() {

        if (!(txtmalzemeAdi.getText().trim().equals(""))&&!(txtmalzemeGrubu.getText().trim().equals(""))
                &&!(txtmalzemeMarkasi.getText().trim().equals(""))&& !(txtmalzemeModeli.getText().trim().equals(""))
                &&!(txtmalzemeFiyati.getText().trim().equals(""))) {
            try {
                String eklemeSorgusu = "INSERT INTO tblmalzemeler (malzemeGrubu,malzemeAltGrubu,"
                        + "malzemeMarkasi,malzemeModeli,malzemeAdi,malzemeFiyati,malzemeParaBirimi,malzemeBirimi,malzemeDataSheet,malzemeSartname)"
                        + "VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
                preparedStatement = baglanti.prepareStatement(eklemeSorgusu);


                preparedStatement.setString(1, txtmalzemeGrubu.getText());
                preparedStatement.setString(2, txtmalzemeAltGrubu.getText());
                preparedStatement.setString(3, txtmalzemeMarkasi.getText());
                preparedStatement.setString(4, txtmalzemeModeli.getText());
                preparedStatement.setString(5, txtmalzemeAdi.getText());
                preparedStatement.setString(6, txtmalzemeFiyati.getText());
                preparedStatement.setString(7, cbparaBirimi.getSelectedItem().toString());                
                preparedStatement.setString(8, cbmalzemeBirimi.getSelectedItem().toString());

                preparedStatement.setString(9, txtmalzemeDataSheet.getText());
                preparedStatement.setString(10, txtmalzemeSartname.getText());                

                preparedStatement.execute();

                malzemeleriTabloyaGetir();
                formuTemizle();
                JOptionPane.showMessageDialog(null, "Kaydetme işlemi\nbaşarılı olarak gerçekleştirildi.", "MESAJ",
                        JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "HATA :" + e, "MESAJ", JOptionPane.ERROR_MESSAGE);

            }
        } else {
            JOptionPane.showMessageDialog(null, "Zorunlu Alanları Doldurunuz.", "MESAJ", JOptionPane.ERROR_MESSAGE);

        }

    }

//    private void tabloyuGuncelle() {
//
//        try {
//            String tabloyuGuncelleSorgusu = "SELECT * FROM tblmalzemeler "
//                    + " ORDER BY malzemeID";
//            preparedStatement = baglanti.prepareStatement(tabloyuGuncelleSorgusu);
//            resultSet = preparedStatement.executeQuery();
//            tableMalzeme.setModel(DbUtils.resultSetToTableModel(resultSet));
//        } catch (Exception e) {
//        }
//    }

    private void formuTemizle() {
        txtmalzemeAdi.setText(null);
        txtmalzemeAltGrubu.setText(null);
        txtmalzemeDataSheet.setText(null);
        txtmalzemeSartname.setText(null);
        txtmalzemeFiyati.setText(null);
        txtmalzemeGrubu.setText(null);
        txtmalzemeMarkasi.setText(null);
        txtmalzemeModeli.setText(null);
        cbmalzemeBirimi.setSelectedIndex(0);
        cbparaBirimi.setSelectedIndex(0);

    }

    private void malzemeSil() {
        if (tableMalzeme.getSelectedRowCount() != 0) {//Tabloda herhangi bir satır seçilmişse silme işleme gerçekleşsin
            Object[] dugmeIsimleri = {"Evet",
                "Hayır"};
            int gelenDeger = JOptionPane.showOptionDialog(rootPane, "Emin misiniz?", "UYARI MESAJI",
                    JOptionPane.YES_NO_CANCEL_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    (new javax.swing.ImageIcon(getClass().getResource("/icons/uyari.png"))),
                    dugmeIsimleri,
                    dugmeIsimleri[1]);


            if (gelenDeger == 0) {

                try {


                    String silmeSorgusu = "DELETE FROM tblmalzemeler WHERE malzemeID = ?";


                    preparedStatement = baglanti.prepareStatement(silmeSorgusu);

                    int satirNumarasi = tableMalzeme.getSelectedRow();
                    //tablodaki o andaki sırası    //ilk kolon sütun
                    preparedStatement.setString(1, tableMalzeme.getModel().getValueAt(satirNumarasi, 0).toString());

                    preparedStatement.execute();

                    JOptionPane.showMessageDialog(null, "Silme işlemi\nbaşarılı olarak gerçekleştirildi.", "MESAJ",
                            JOptionPane.INFORMATION_MESSAGE);

                    malzemeleriTabloyaGetir();
                    formuTemizle();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "HATA :" + e, "MESAJ", JOptionPane.ERROR_MESSAGE);

                }



            } else if (gelenDeger == 1) {
            }
        } else {
            JOptionPane.showMessageDialog(null, "HATA MEYDA GELDİ\nLütfen Bir Seçim Yapınız.", "MESAJ", JOptionPane.ERROR_MESSAGE);
        }



    }

    private void malzemeGuncelle() {
        if (!(txtmalzemeAdi.getText().trim().equals(""))&&!(txtmalzemeGrubu.getText().trim().equals(""))
                &&!(txtmalzemeMarkasi.getText().trim().equals(""))&& !(txtmalzemeModeli.getText().trim().equals(""))
                &&!(txtmalzemeFiyati.getText().trim().equals(""))) {
            try {
                String guncellemeSorgusu = "UPDATE tblmalzemeler SET "
                        + " malzemeGrubu = ?, "
                        + " malzemeAltGrubu = ?, "
                        + " malzemeMarkasi = ?, "
                        + " malzemeModeli = ?, "
                        + " malzemeAdi = ?, "
                        + " malzemeFiyati = ?, "
                        + " malzemeParaBirimi = ?, "
                        + " malzemeBirimi = ?, "
                        + " malzemeDataSheet = ?, "
                        + " malzemeSartname = ? "                        
                        + " WHERE malzemeID = ? ";

                preparedStatement = baglanti.prepareStatement(guncellemeSorgusu);


                preparedStatement.setString(1, txtmalzemeGrubu.getText());
                preparedStatement.setString(2, txtmalzemeAltGrubu.getText());
                preparedStatement.setString(3, txtmalzemeMarkasi.getText());
                preparedStatement.setString(4, txtmalzemeModeli.getText());
                preparedStatement.setString(5, txtmalzemeAdi.getText());
                preparedStatement.setString(6, txtmalzemeFiyati.getText());
                preparedStatement.setString(7, cbparaBirimi.getSelectedItem().toString());
                preparedStatement.setString(8, cbmalzemeBirimi.getSelectedItem().toString());
                preparedStatement.setString(9, txtmalzemeDataSheet.getText());
                preparedStatement.setString(10, txtmalzemeSartname.getText());                

                int satirNumarasi = tableMalzeme.getSelectedRow();
                //tablodaki o andaki sırası    //ilk kolon sütun
                preparedStatement.setString(11, tableMalzeme.getModel().getValueAt(satirNumarasi, 0).toString());

                //GÜNCELLEMEYE ÖZEL
                preparedStatement.executeUpdate();

                JOptionPane.showMessageDialog(null, "Gücellenme işlemi\nbaşarılı olarak gerçekleştirildi.", "MESAJ",
                        JOptionPane.INFORMATION_MESSAGE);

                malzemeleriTabloyaGetir();
                formuTemizle();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "HATA MEYDA GELDİ\nLütfen Bir Seçim Yapınız.", "MESAJ", JOptionPane.ERROR_MESSAGE);

            }
        } else {
            JOptionPane.showMessageDialog(null, "Zorunlu Alanları Doldurunuz.", "MESAJ", JOptionPane.ERROR_MESSAGE);

        }

    }

    private void tablodakiMalzemeleriTxtFieldlaraGetir() {
        int satirNumarasi = tableMalzeme.getSelectedRow();
        //KOLON SÜTUN

        txtmalzemeGrubu.setText(tableMalzeme.getModel().getValueAt(satirNumarasi, 1).toString());
        txtmalzemeAltGrubu.setText(tableMalzeme.getModel().getValueAt(satirNumarasi, 2).toString());
        txtmalzemeMarkasi.setText(tableMalzeme.getModel().getValueAt(satirNumarasi, 3).toString());
        txtmalzemeModeli.setText(tableMalzeme.getModel().getValueAt(satirNumarasi, 4).toString());
        txtmalzemeAdi.setText(tableMalzeme.getModel().getValueAt(satirNumarasi, 5).toString());
        txtmalzemeFiyati.setText(tableMalzeme.getModel().getValueAt(satirNumarasi, 6).toString());
        cbparaBirimi.setSelectedItem(tableMalzeme.getModel().getValueAt(satirNumarasi, 7).toString());
        cbmalzemeBirimi.setSelectedItem(tableMalzeme.getModel().getValueAt(satirNumarasi, 8).toString());
        txtmalzemeDataSheet.setText(tableMalzeme.getModel().getValueAt(satirNumarasi, 9).toString());
        txtmalzemeSartname.setText(tableMalzeme.getModel().getValueAt(satirNumarasi, 10).toString());        

        btnMalzemeSil.setEnabled(true);
        btnMalzemeDuzenle.setEnabled(true);
        kullanicininYetkileriniBul();
    }

    private void aramaYap() {
        try {
            formuTemizle();

            String aramaSorgusu = "SELECT  * FROM tblmalzemeler "
                    + "WHERE  malzemeAdi LIKE ? AND   malzemeMarkasi LIKE ?";
            preparedStatement = baglanti.prepareStatement(aramaSorgusu);
            preparedStatement.setString(1, txtAramaMalzemeAdi.getText() + "%");
            preparedStatement.setString(2, txtAramaMalzemeMarkasi.getText() + "%");
            resultSet = preparedStatement.executeQuery();
            tableMalzeme.setModel(DbUtils.resultSetToTableModel(resultSet));
               tableMalzeme.getModel().addTableModelListener(new TableModelListener(){
                @Override
                public void tableChanged(TableModelEvent e) {
                    aramaYap();
                }                       
            });


            if (tableMalzeme.getRowCount() > 0) {
                lblAramaMesaj.setText("Kayıtlar gösteriliyor.");
            } else {
                lblAramaMesaj.setText("Aranılan kayıt bulunamadı.");
            }

            if (txtAramaMalzemeAdi.getText().equals("") && txtAramaMalzemeMarkasi.getText().equals("")) {
                lblAramaMesaj.setText("Mesaj : ");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "HATA :" + e, "MESAJ", JOptionPane.ERROR_MESSAGE);

        }
    }

    private void malzemeYazdir() {
        try {
            String MALZEMEADI = txtAramaMalzemeAdi.getText() + "%";
            String MALZEMEMARKASI = txtAramaMalzemeMarkasi.getText() + "%";

            
            
//            SELECT malzemeGrubu,malzemeAltGrubu,malzemeMarkasi,malzemeModeli,malzemeAdi,malzemeFiyati,malzemeParaBirimi,malzemeBirimi FROM tblmalzemeler
            String raporSorgusu = "SELECT  * FROM tblmalzemeler "
                    + " WHERE malzemeAdi LIKE '" + MALZEMEADI + "' AND  malzemeMarkasi LIKE '" + MALZEMEMARKASI + "' ";

            JasperDesign jasperDesign = JRXmlLoader.load("malzemereport.jrxml");


            JRDesignQuery designQuery = new JRDesignQuery();
            designQuery.setText(raporSorgusu);
            jasperDesign.setQuery(designQuery);
            JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, baglanti);
            JasperViewer.viewReport(jasperPrint, false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "HATA :", "MESAJ", JOptionPane.ERROR_MESSAGE);
        }

    }

    private void kullanicininYetkileriniBul() {
        try {

            preparedStatement = baglanti.prepareStatement("SELECT * FROM tblkullanicilar WHERE kullaniciAdi=?");
             preparedStatement.setString(1, AnaGirisiPaneliGUI.txtKullaniciAdi.getText());
                   resultSet = preparedStatement.executeQuery();
                  String yetki=null;
                   while (resultSet.next()) {
                      yetki= resultSet.getString("kullaniciYetki");
                   }
                   
                   if(!(yetki.contains("Malzeme Ekleme"))){
                       btnMalzemeKaydet.setEnabled(false);
                       btnAcMalzemeImportGUI.setEnabled(false);
                       menuItemImportCsv.setEnabled(false);
                   }
                   
                      if(!(yetki.contains("Malzeme Silme ve Güncelleme"))){
                       btnMalzemeDuzenle.setEnabled(false);
                       btnMalzemeSil.setEnabled(false);
                       btnDataSheetSec.setEnabled(false);
                   }
     

        } catch (Exception e) {
        }
    }
}
