/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.aksoyali;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Ali
 */
public class YoneticiBilgiDegistirGUI extends javax.swing.JFrame {

    /**
     * Creates new form YoneticiBilgiDegistirGUI
     */
    public YoneticiBilgiDegistirGUI() {
        initComponents();
            this.setLocationRelativeTo(getRootPane());//Frame ekranın ortasında açılır
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblYoneticiEskiKullaniciAdi = new javax.swing.JLabel();
        lblYoneticiEskiParola = new javax.swing.JLabel();
        txtYoneticiEskiKullaniciAdi = new javax.swing.JTextField();
        lblYoneticiYeniKullaniciAdi = new javax.swing.JLabel();
        txtYoneticiYeniKullaniciAdi = new javax.swing.JTextField();
        lblYoneticiYeniParola = new javax.swing.JLabel();
        btnYoneticiBilgiDegistir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtlYoneticiEskiParola = new javax.swing.JPasswordField();
        txtYoneticiYeniParola = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("YÖNETİCİ BİLGİ DÜZENLE");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        lblYoneticiEskiKullaniciAdi.setText("Mevcut Kullancı Adınız");

        lblYoneticiEskiParola.setText("Mevcut Parolanız");

        lblYoneticiYeniKullaniciAdi.setText("Yeni Kullanıcı Adı");

        lblYoneticiYeniParola.setText("Yeni Parola");

        btnYoneticiBilgiDegistir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/degistir.png"))); // NOI18N
        btnYoneticiBilgiDegistir.setText("DEĞİŞTİR");
        btnYoneticiBilgiDegistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYoneticiBilgiDegistirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("*");
        jLabel1.setToolTipText("ZORUNLU ALAN");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("*");
        jLabel2.setToolTipText("ZORUNLU ALAN");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("*");
        jLabel3.setToolTipText("ZORUNLU ALAN");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("*");
        jLabel4.setToolTipText("ZORUNLU ALAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblYoneticiEskiKullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblYoneticiEskiParola, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(57, 57, 57)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtYoneticiEskiKullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtlYoneticiEskiParola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGap(159, 159, 159)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtYoneticiYeniKullaniciAdi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtYoneticiYeniParola, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnYoneticiBilgiDegistir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblYoneticiYeniParola, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblYoneticiYeniKullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtYoneticiEskiKullaniciAdi, txtYoneticiYeniKullaniciAdi, txtYoneticiYeniParola, txtlYoneticiEskiParola});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblYoneticiEskiKullaniciAdi)
                    .addComponent(txtYoneticiEskiKullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblYoneticiEskiParola)
                    .addComponent(jLabel3)
                    .addComponent(txtlYoneticiEskiParola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jSeparator1)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblYoneticiYeniKullaniciAdi)
                    .addComponent(jLabel2)
                    .addComponent(txtYoneticiYeniKullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblYoneticiYeniParola)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtYoneticiYeniParola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnYoneticiBilgiDegistir)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Connection baglanti = null;
    ResultSet resultSet = null;
     PreparedStatement preparedStatement = null;
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       baglanti=Mysqlbaglantisi.baglan();

    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
      if (baglanti != null) {

            try {
                baglanti.close();
            } catch (Exception e) {
            }

        }

        if (resultSet != null) {
            try {
                resultSet.close();
            } catch (Exception e) {
            }
        }


        if (preparedStatement != null) {
            try {
                preparedStatement.close();
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnYoneticiBilgiDegistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYoneticiBilgiDegistirActionPerformed
        yoneticiBigiGuncelle();
    }//GEN-LAST:event_btnYoneticiBilgiDegistirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YoneticiBilgiDegistirGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YoneticiBilgiDegistirGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YoneticiBilgiDegistirGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YoneticiBilgiDegistirGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YoneticiBilgiDegistirGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnYoneticiBilgiDegistir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblYoneticiEskiKullaniciAdi;
    private javax.swing.JLabel lblYoneticiEskiParola;
    private javax.swing.JLabel lblYoneticiYeniKullaniciAdi;
    private javax.swing.JLabel lblYoneticiYeniParola;
    private javax.swing.JTextField txtYoneticiEskiKullaniciAdi;
    private javax.swing.JTextField txtYoneticiYeniKullaniciAdi;
    private javax.swing.JPasswordField txtYoneticiYeniParola;
    private javax.swing.JPasswordField txtlYoneticiEskiParola;
    // End of variables declaration//GEN-END:variables

    private void yoneticiBigiGuncelle() {
         if (!(txtYoneticiYeniKullaniciAdi.getText().trim().equals("")) &&
                 !(txtYoneticiYeniParola.getText().trim().equals("")) ) {
             
          try {

              String kullaniciGirisiSorgusu = "SELECT * FROM tblyonetici WHERE yoneticiKullaniciAdi = ? AND yoneticiParola = ?";
            preparedStatement = baglanti.prepareStatement(kullaniciGirisiSorgusu);
            preparedStatement.setString(1, txtYoneticiEskiKullaniciAdi.getText());
            preparedStatement.setString(2, txtlYoneticiEskiParola.getText());

            resultSet = preparedStatement.executeQuery();

            if (resultSet.next()) {
                  try {


                String guncellemeSorgusu = "UPDATE tblyonetici SET "
                        + " yoneticiKullaniciAdi = ?, "
                        + " yoneticiParola = ? "

                        + " WHERE yoneticiID = ? ";

                preparedStatement = baglanti.prepareStatement(guncellemeSorgusu);

                preparedStatement.setString(1, txtYoneticiYeniKullaniciAdi.getText());
                preparedStatement.setString(2, txtYoneticiYeniParola.getText());
                  preparedStatement.setString(3, "1");
                preparedStatement.executeUpdate();

                JOptionPane.showMessageDialog(null, "Gücellenme işlemi\nbaşarılı olarak gerçekleştirildi.", "MESAJ",
                        JOptionPane.INFORMATION_MESSAGE);

                formuTemizle();
            } catch (Exception e) {
                            JOptionPane.showMessageDialog(null, "HATA", "MESAJ",
                        JOptionPane.ERROR_MESSAGE); 
            }
            }
            else{
               JOptionPane.showMessageDialog(null, "Geçersiz Kullanıcı Adı veya Parola", "MESAJ",
                        JOptionPane.ERROR_MESSAGE);
            }
          }catch (Exception e){
                           JOptionPane.showMessageDialog(null, "HATA", "MESAJ",
                        JOptionPane.ERROR_MESSAGE);      
          }
                
                
         } else {
            JOptionPane.showMessageDialog(null, "Zorunlu Alanları Doldurunuz.", "MESAJ", JOptionPane.ERROR_MESSAGE);

        }
    }

    private void formuTemizle() {
      txtYoneticiEskiKullaniciAdi.setText(null);
      txtYoneticiYeniKullaniciAdi.setText(null);
      txtYoneticiYeniParola.setText(null);
      txtlYoneticiEskiParola.setText(null);
    }
}
